@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\heyob\Documents\Codex\2026-05-25\i-want-to-make-one-app\node_modules\.pnpm\vite@6.4.2_@types+node@25.9.1\node_modules\vite\node_modules;C:\Users\heyob\Documents\Codex\2026-05-25\i-want-to-make-one-app\node_modules\.pnpm\vite@6.4.2_@types+node@25.9.1\node_modules;C:\Users\heyob\Documents\Codex\2026-05-25\i-want-to-make-one-app\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\heyob\Documents\Codex\2026-05-25\i-want-to-make-one-app\node_modules\.pnpm\vite@6.4.2_@types+node@25.9.1\node_modules\vite\node_modules;C:\Users\heyob\Documents\Codex\2026-05-25\i-want-to-make-one-app\node_modules\.pnpm\vite@6.4.2_@types+node@25.9.1\node_modules;C:\Users\heyob\Documents\Codex\2026-05-25\i-want-to-make-one-app\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\vite\bin\vite.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\vite\bin\vite.js" %*
)
